version: '3.7'

services:
  django:
    build: .
    container_name: ct22-django-dev-container
    image: ct22-django-dev-image
    ports:
      - 8000:8000
    depends_on:
      - postgres
    volumes:
      - .:/code
      - ../ct22-volumes/static:/ct22-volumes/static
      - ../ct22-volumes/media:/ct22-volumes/media
      - ../ct22-volumes/bucket:/bucket
      - ../ct22-volumes/logs/ct-web:/var/log/ct-web
    command: /srv/start
    restart: always
    #env_file:
    #  - .env
    environment:
      - WEB_ENV=dev
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=cameratrap
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
  postgres:
    image: postgres:13-alpine
    shm_size: '1g'
    #build:
    #  context: .
    #  dockerfile: ./compose/production/postgres/Dockerfile
    #image: ct-postgres-image
    container_name: ct22-postgres-container
    restart: always
    volumes:
      - ../ct22-volumes/pgdata:/var/lib/postgresql/data/pgdata
      - ../ct22-volumes/bucket:/bucket
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=cameratrap
      - PGDATA=/var/lib/postgresql/data/pgdata
    #env_file:
    #  - .env
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
  redis:
    image: redis:6-alpine
    restart: always
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  celery:
    restart: unless-stopped
    build:
      context: .
    container_name: ct22-celery-dev-container
    image: ct22-django-dev-image
    command: /root/.local/bin/celery -A conf worker -l info
    volumes:
      - .:/code
      - ../ct22-volumes/media:/ct22-volumes/media
      - ../ct22-volumes/logs/ct-web:/var/log/ct-web
    depends_on:
      - redis
      - django
    environment:
      - WEB_ENV=dev
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=cameratrap
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
